export const initialRecipesTop = [
  {
    title: 'title1',
    country: 'country1',
    description: 'description1',
    ingredients: ['ingr1', 'ingr2', 'ingr3'],
    instructions: 'instructions1',
    favorites: 200,
    clicks: 100,
  },

  {
    title: 'title2',
    country: 'country2',
    description: 'description2',
    ingredients: ['ingr5', 'ingr2', 'ingr1'],
    instructions: 'instructions2',
    favorites: 500,
    clicks: 300,
  },
  {
    title: 'title5',
    country: 'country5',
    description: 'description5',
    ingredients: ['ingr1', 'ingr2', 'ingr4'],
    instructions: 'instructions5',
    favorites: 10,
    clicks: 6,
  },
  {
    title: 'title3',
    country: 'country3',
    description: 'description3',
    ingredients: ['ingr6', 'ingr7', 'ingr1'],
    instructions: 'instructions1',
    favorites: 400,
    clicks: 70,
  },
  {
    title: 'title4',
    country: 'country4',
    description: 'description2',
    ingredients: ['ingr5', 'ingr4', 'ingr9'],
    instructions: 'instructions4',
    favorites: 600,
    clicks: 432,
  },
];
