
name: CI

on:
  push:
    branches: [ "master" ]


  

jobs:
  
  build:
    env:
      platform: aws
      region: us-east-1
      account: 1234125
    runs-on: ubuntu-latest

    steps:
        - name: "Display Messaje"
          run: echo "Hello"

        - name: "Showing env variables"
          if: ${{env.platform == 'azure'}}
          run: |
            echo "Platform: ${{env.platform}}"
            echo "Region: ${{env.region}}" 
            echo "Account: ${{env.account}}"
