
name: CI

on:
  push:
    branches: [ "master" ]


  

jobs:
  
  build:
    env:
      platform: aws
      region: us-east-1
      account: 1234125
    runs-on: ubuntu-latest

    steps:
        - name: "Display Messaje"
          run: echo "Hello"

        - name: "Showing env variables"
          run: |
            echo "Platform: $platform"
            echo "Region: $region" 
            echo "Account: $account"
