# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build: #it can be named like u want
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # necessary to instal dependencies. it returns the repository infomation(folders,file)  
      - uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'pnpm'
      - run: pnpm ci
      - run: pnpm build
 